-- MySQL Script generated by MySQL Workbench
-- Mon Mar 15 01:28:51 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mascoshop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mascoshop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mascoshop` DEFAULT CHARACTER SET utf8 ;
USE `mascoshop` ;

-- -----------------------------------------------------
-- Table `mascoshop`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mascoshop`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `pass` VARCHAR(100) NOT NULL,
  `pais` VARCHAR(45) NULL,
  `localidad` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `category` INT NULL,
  `avatar` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mascoshop`.`sub_categorys`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mascoshop`.`sub_categorys` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mascoshop`.`categorys`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mascoshop`.`categorys` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mascoshop`.`cate_sub`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mascoshop`.`cate_sub` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sub_category_id` INT NULL,
  `category_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `sub_category_id_idx` (`sub_category_id` ASC),
  INDEX `category_id_idx` (`category_id` ASC),
  CONSTRAINT `sub_category_id`
    FOREIGN KEY (`sub_category_id`)
    REFERENCES `mascoshop`.`sub_categorys` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `category_id`
    FOREIGN KEY (`category_id`)
    REFERENCES `mascoshop`.`categorys` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mascoshop`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mascoshop`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `precio` INT NOT NULL,
  `stock` INT NOT NULL,
  `discount` INT NOT NULL,
  `description` VARCHAR(300) NOT NULL,
  `cate_sub_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `cate_sub_id_idx` (`cate_sub_id` ASC),
  CONSTRAINT `cate_sub_id`
    FOREIGN KEY (`cate_sub_id`)
    REFERENCES `mascoshop`.`cate_sub` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mascoshop`.`product_images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mascoshop`.`product_images` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product_name` VARCHAR(45) NOT NULL,
  `product_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `product_id_idx` (`product_id` ASC),
  CONSTRAINT `product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `mascoshop`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mascoshop`.`cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mascoshop`.`cart` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `producto_id` INT NULL,
  `cliente_id` INT NULL,
  `cantidad` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `producto_id_idx` (`producto_id` ASC),
  INDEX `cliente_id_idx` (`cliente_id` ASC),
  CONSTRAINT `producto_id`
    FOREIGN KEY (`producto_id`)
    REFERENCES `mascoshop`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cliente_id`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `mascoshop`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mascoshop`.`purcheses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mascoshop`.`purcheses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `prod_id` INT NULL,
  `user_id` INT NULL,
  `fecha` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `prod_id_idx` (`prod_id` ASC),
  INDEX `user_id_idx` (`user_id` ASC),
  CONSTRAINT `prod_id`
    FOREIGN KEY (`prod_id`)
    REFERENCES `mascoshop`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `mascoshop`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
