-- MySQL Script generated by MySQL Workbench
-- Wed Mar 17 01:53:24 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mascoshop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mascoshop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mascoshop` DEFAULT CHARACTER SET utf8 ;
USE `mascoshop` ;

-- -----------------------------------------------------
-- Table `mascoshop`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mascoshop`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `pass` VARCHAR(100) NOT NULL,
  `pais` VARCHAR(45) NULL,
  `localidad` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `category` VARCHAR(45) NULL,
  `avatar` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mascoshop`.`categorys`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mascoshop`.`categorys` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mascoshop`.`sub_categorys`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mascoshop`.`sub_categorys` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mascoshop`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mascoshop`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `precio` INT NOT NULL,
  `stock` INT NOT NULL,
  `discount` INT NOT NULL,
  `description` VARCHAR(300) NOT NULL,
  `category_id` INT NULL,
  `subcategory_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `category_id_idx` (`category_id` ASC),
  INDEX `subcategory_id_idx` (`subcategory_id` ASC),
  CONSTRAINT `category_id`
    FOREIGN KEY (`category_id`)
    REFERENCES `mascoshop`.`categorys` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `subcategory_id`
    FOREIGN KEY (`subcategory_id`)
    REFERENCES `mascoshop`.`sub_categorys` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mascoshop`.`product_images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mascoshop`.`product_images` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product_name` VARCHAR(45) NOT NULL,
  `product_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `product_id_idx` (`product_id` ASC),
  CONSTRAINT `product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `mascoshop`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mascoshop`.`purchases`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mascoshop`.`purchases` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `client_id` INT NULL,
  `product_purch_id` INT NULL,
  `fecha` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `client_id_idx` (`client_id` ASC),
  INDEX `product_purch_id_idx` (`product_purch_id` ASC),
  CONSTRAINT `client_id`
    FOREIGN KEY (`client_id`)
    REFERENCES `mascoshop`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `product_purch_id`
    FOREIGN KEY (`product_purch_id`)
    REFERENCES `mascoshop`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mascoshop`.`cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mascoshop`.`cart` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL,
  `prod_id` INT NULL,
  `cantidad` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id_idx` (`user_id` ASC),
  INDEX `prod_id_idx` (`prod_id` ASC),
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `mascoshop`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `prod_id`
    FOREIGN KEY (`prod_id`)
    REFERENCES `mascoshop`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
