-- MySQL Script generated by MySQL Workbench
-- Sun Mar  7 10:57:30 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mascoshop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mascoshop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mascoshop` DEFAULT CHARACTER SET utf8 ;
USE `mascoshop` ;

-- -----------------------------------------------------
-- Table `mascoshop`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mascoshop`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `pass` VARCHAR(45) NOT NULL,
  `pais` VARCHAR(45) NULL,
  `localidad` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `category` INT NULL,
  `avatar` VARCHAR(45) NOT NULL,
  `exist` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mascoshop`.`categorys`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mascoshop`.`categorys` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mascoshop`.`subcategorys`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mascoshop`.`subcategorys` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mascoshop`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mascoshop`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category_id` INT NULL,
  `subcategory_id` INT NULL,
  `name` VARCHAR(45) NOT NULL,
  `precio` INT NOT NULL,
  `stock` INT NOT NULL,
  `discount` INT NOT NULL,
  `description` VARCHAR(200) NOT NULL,
  `img` VARCHAR(45) NOT NULL,
  `exist` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `category_id_idx` (`category_id` ASC),
  INDEX `subcategory_id_idx` (`subcategory_id` ASC),
  CONSTRAINT `category_id`
    FOREIGN KEY (`category_id`)
    REFERENCES `mascoshop`.`categorys` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `subcategory_id`
    FOREIGN KEY (`subcategory_id`)
    REFERENCES `mascoshop`.`subcategorys` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mascoshop`.`purchases`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mascoshop`.`purchases` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `producto_id` INT NULL,
  `cliente_id` INT NULL,
  `fecha` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `producto_id_idx` (`producto_id` ASC),
  INDEX `cliente_id_idx` (`cliente_id` ASC),
  CONSTRAINT `producto_id`
    FOREIGN KEY (`producto_id`)
    REFERENCES `mascoshop`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cliente_id`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `mascoshop`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
